DROP DATABASE IF EXISTS ITIS;
CREATE DATABASE IF NOT EXISTS ITIS CHARACTER SET latin1 collate = latin1_bin;
USE ITIS;
source ITIS.sql

drop table change_comments;
drop table change_operations;
drop table change_tracks;
drop table chg_operation_lkp;
alter table comments change column comment_id id int(11);
alter table comments change column commentator expert varchar(100);
alter table comments change column comment_detail comment text;
alter table comments change column comment_time_stamp time datetime;
alter table comments drop column update_date;
alter table experts drop column expert_id_prefix;
alter table experts change column expert_id id int(11);
alter table experts change column exp_comment area varchar(500);
alter table experts drop column update_date;
alter table geographic_div rename to regions;
alter table regions change column tsn taxon int(11);
alter table regions change column geographic_value region varchar(45);
alter table regions drop column update_date;
drop table hierarchy;
alter table jurisdiction rename to areas;
alter table areas change column tsn taxon int(11);
alter table areas change column jurisdiction_value area varchar(30);
alter table areas drop column update_date;
alter table kingdoms change column kingdom_id id int(11);
alter table kingdoms change column kingdom_name kingdom char(10);
drop table longnames;
alter table nodc_ids change column tsn taxon int(11);
alter table nodc_ids drop column update_date;
alter table other_sources rename to sources;
alter table sources drop column source_id_prefix;
alter table sources drop column acquisition_date;
alter table sources drop column update_date;
alter table sources change column source_id id int(11);
alter table sources change column source_type type char(10);
alter table sources change column source_comment comment varchar(500);
alter table publications drop column pub_id_prefix;
alter table publications change column publication_id id int(11);
alter table publications change column publication_name name varchar(255);
alter table publications change column listed_pub_date date_listed date;
alter table publications change column pub_place place varchar(40);
alter table publications change column pub_comment comment varchar(500);
alter table publications drop column update_date;
alter table reference_links change column tsn taxon int(11);
alter table reference_links drop column update_date;
alter table synonym_links drop column update_date ;
alter table synonym_links change column tsn taxon int(11);
alter table synonym_links change column tsn_accepted taxon_accepted int(11);
alter table taxonomic_units rename to taxa;
alter table taxa change column tsn id int(11);
alter table taxa drop column update_date;
alter table taxon_authors_lkp drop column update_date;
alter table taxon_unit_types drop column update_date;
alter table vern_ref_links drop column update_date;
alter table tu_comments_links drop column update_date;
alter table vern_ref_links change column tsn taxon int(11);
alter table vern_ref_links change column vern_id vernacular int(11);
alter table vern_ref_links change column doc_id_prefix reference_type char(3);
alter table vern_ref_links change column documentation_id reference int(11);
alter table vern_ref_links rename to vernacular_to_taxon;
alter table reference_links change column doc_id_prefix reference_type char(3);
alter table taxa change column parent_tsn parent int(11);
alter table taxa drop column initial_time_stamp ;
alter table taxa drop column unit_ind1;
alter table taxa drop column unit_ind2;
alter table taxa drop column unit_ind3;
alter table taxa drop column unit_ind4;
alter table taxa change column unit_name1 name_1 varchar(35);
alter table taxa change column unit_name2 name_2 varchar(35);
alter table taxa change column unit_name3 name_3 varchar(35);
alter table taxa change column unit_name4 name_4 varchar(35);
alter table taxa change unnamed_taxon_ind unnamed char(1);
alter table taxa change kingdom_id kingdom smallint(6);
alter table taxa change credibility_rtng credibility varchar(40);
alter table taxa change completeness_rtng completeness char(10);
alter table taxa change currency_rating currency char(7);
update taxa set currency = NULL where currency= 'unknown';
update taxa set currency = NULL where currency= '';
alter table taxa change column taxon_author_id author_taxon int(11);
alter table taxa change column hybrid_author_id author_hybrid int(11);
alter table tu_comments_links rename to comment_to_taxon;
alter table comment_to_taxon change column tsn taxon int(11);
alter table comment_to_taxon change column comment_id comment int(11);
alter table taxon_authors_lkp change column taxon_author_id author_taxon int(11);
alter table taxon_authors_lkp change column kingdom_id kingdom smallint(6);
alter table taxon_authors_lkp change column taxon_author value varchar(100);
alter table taxon_authors_lkp rename to authors;
alter table strippedauthor rename to authors_stripped;
alter table authors_stripped change column taxon_author_id author_taxon int(11);
alter table authors_stripped change column shortauthor value varchar(100);
alter table authors change column author_taxon author int(11);
alter table authors_stripped change column author_taxon author int(11);
alter table authors change column author id int(11);
alter table authors change column value author varchar(100);
alter table authors add column author_stripped varchar(100);
alter table authors_stripped change column author id int(11);
alter table authors_stripped change column value author varchar(100);
alter table synonym_links rename to synonyms;
alter table vernaculars change column vernacular_name vernacular varchar(80);
alter table vernaculars drop column update_date;
alter table vernaculars change column vern_id id int(11);
alter table vernaculars change column tsn taxon int(11);
update vernaculars set language = 'English' where language = 'unspecified';
alter table vernaculars drop column approved_ind ;
alter table nodc_ids rename to NODC;
alter table NODC change column nodc_id id char(12);
alter table taxon_unit_types rename to taxonomic_units;
alter table taxonomic_units change column rank_id id smallint(6);
alter table taxonomic_units change column kingdom_id kingdom int(11);
alter table taxonomic_units change column rank_name name char(15);
alter table taxonomic_units change column dir_parent_rank_id parent_direct smallint(6);
alter table taxonomic_units change column req_parent_rank_id parent_required smallint(6);
alter table reference_links rename to references_;
alter table references_ change column reference_type type char(3);
alter table references_ drop column vernacular_name;
alter table references_ drop column change_track_id;
alter table references_ drop column original_desc_ind ;
alter table references_ drop column init_itis_desc_ind;
alter table references_ change column documentation_id reference int(11);
alter table taxa drop column author_hybrid;
alter table authors change column author_stripped stripped varchar(100);
create table temp as select  authors.id, kingdom, authors.author, authors_stripped.author as stripped from authors join authors_stripped on authors.id = authors_stripped.id;
drop table authors;
drop table authors_stripped;
alter table temp rename to authors;
alter table taxa change column author_taxon author int(11);
alter table taxa change column rank_id taxonomic_rank smallint(6);
create table temp as select  id div 5 as id, kingdom, parent_direct div 5 as parent_direct, parent_required div 5 as parent_required, name from taxonomic_units order by id, kingdom;
ALTER TABLE temp add primary key (id, kingdom);
drop table taxonomic_units;
alter table temp rename to taxonomic_units;
update sources set type = 'website' where type = '2011';
update sources set type = 'PDF' where type = 'pdf file';
update sources set type = 'CD-ROM' where type = 'CD ROM';
update sources set type = 'CD-ROM' where type = 'disk file';
drop table reviews;
update regions set region = 'Europe & Northern Asia (excluding China)' where region like 'Europe and%';
create unique index taxaindex on taxa (id);
create unique index NODCindex on NODC (taxon);
create index index2 on NODC (taxon);
create table temp as select taxa.*, NODC.id as NODC from NODC right join taxa on NODC.taxon = taxa.id;
drop table taxa;
alter table temp rename to taxa;
drop table NODC;
create unique index i on comments (id);
create unique index i on experts (id);
create unique index i on publications (id);
alter table publications change column actual_pub_date date_actual date;
create unique index i on sources (id);
alter table taxa drop column phylo_sort_seq ;
update taxa set name_3 = name_4 where name_4 is not null;
alter table taxa drop column name_4 ;
update taxa set name_2 = name_3 where name_3 is not null;
alter table taxa drop column name_3 ;
update taxa set name_1 = name_2 where name_2 is not null;
alter table taxa drop column name_2 ;
alter table taxa change column name_1 name varchar(35);
create table area ( id int auto_increment not null, area varchar(30), primary key (id));
insert into area (area) select distinct area from areas order by area;
alter table areas rename to taxon_to_area;
alter table area rename to areas;
alter table taxon_to_area rename to area_to_taxon;
create table origins ( id int auto_increment not null, origin varchar(30), primary key (id));
insert into origins (origin) select distinct origin from area_to_taxon order by origin;
alter table origins change column id id tinyint;
alter table areas change column id id tinyint;
alter table area_to_taxon rename to taxon_to_area_origin;
create table temp as select taxon, areas.id as area, origins.id as origin from (taxon_to_area_origin join areas on taxon_to_area_origin.area = areas.area) join origins on taxon_to_area_origin.origin = origins.origin;
alter table temp add primary key (taxon, area);
drop table taxon_to_area_origin;
alter table temp rename to taxon_to_area_origin;
alter table authors modify kingdom tinyint not null;
alter table authors modify author varchar(100) not null;
alter table authors modify stripped varchar(100) not null;
alter table areas modify area varchar(30) not null;
alter table comments modify expert varchar(100) not null;
alter table comments modify comment text not null;
alter table comments modify time datetime not null;
update comments set expert = 'Zoonomen website' where expert like 'Zoonomen%';
update comments set expert = 'Todd McConchie, ITIS Data Development Technician' where expert like 'Todd McConchie%';
update comments set expert = 'Todd C. McConchie, ITIS Data Development Technician' where expert like 'Todd McConchie%';
update comments set expert = 'Todd McConchie, ITIS Data Development Technician' where expert like 'Todd McConchei%';
update comments set expert = 'Thomas Orrell, ITIS Data Development Technician' where expert like '%Orrell%';
update comments set expert = 'S. A. Slipinski' where expert like '%Slipinski%';
update comments set expert = 'Shabnam Mohammadi, ITIS Data Development Technician' where expert like '%Mohammadi%';
update comments set expert = 'S.N. Alexander, ITIS Data Development Technician' where expert like '%Alexander%';
update comments set expert = 'Richard C. Banks' where expert like '%C. Banks%';
update comments set expert = 'Todd C. McConchie, ITIS Data Development Technician' where expert like 'Todd%McConch%';
update comments set expert = 'Andrew K. Townesmith, ITIS Data Development Technician' where expert like '%Townesmith%';
update comments set expert = 'Wilson & Reeder, eds. (2005)' where expert like '%Reeder%';
update comments set expert = 'Scott Redhead' where expert like '%Redhead%';
delete from comments where expert like "%?%";
update comments set expert = 'Amanda Treher, ITIS Data Development Technician' where expert like '%Treher%';
update comments set expert = 'Avid F. Mitchell, ITIS Data Development Technician' where expert like '%F. Mitch%';
update comments set expert = 'Daniel Perez-Gelabert, ITIS Data Development Technician' where expert like '%Gelaber%';
update comments set expert = 'David Nicolson, ITIS Data Development Technician' where expert like '%Nicolson%';
update comments set expert = 'Elizabeth Eubanks, ITIS Data Development Technician' where expert like '%eubanks%';
update comments set expert = 'Estelle Yoo, ITIS Data Development Technician' where expert like '%le yoo%';
update comments set expert = 'F. Christian Thomson' where expert like 'F. Christian Thom%';
update comments set expert = 'H. Banford, NMFS-NEFSC, ITIS Data Development Technician' where expert like '%banfo%';
update comments set expert = 'Quintin Gravatt, ITIS Data Development Technician' where expert like '%quint%';
update comments set expert = 'Payal Dharia, ITIS Data Development Technician' where expert like '%dhar%';
update comments set expert = 'Norman F. Johnson' where expert like 'norman%john%';
update comments set expert = ' Nishida, G. M., 1994' where expert like 'nishida%';
update comments set expert = 'Natapot Warrit, ITIS Data Development Technician' where expert like '%Natapot Warri%';
update comments set expert = 'Michael J. Sweeney' where expert like 'Michael J. Swee%';
update comments set expert = 'John C. Morse' where expert like 'John C. Morse%';
update comments set expert = 'Jerry D. Hardy' where expert like 'Jerry D. Hardy%';
update comments set expert = 'Jenny K. Archibald' where expert like 'Jenny K. Ar%';
update comments set expert = 'Jerry Hardy, ITIS Data Development Technician' where expert like 'J%Hardy%';
update comments set expert = 'Herrick Brown, ITIS Data Development Technician' where expert like 'Herrick%Brown%';
update comments set expert = 'G. M. Nishida, 1994' where expert like '%Nishida%';
alter table kingdoms drop column update_date;
update taxa set name_usage = 'valid' where name_usage = 'accepted'
update taxa set name_usage = 'invalid' where name_usage = 'not accepted';
alter table taxa change column name_usage valid varchar(12);
update taxa set valid = 'N' where valid = 'invalid';
update taxa set valid = 'Y' where valid = 'valid';
alter table taxa change column valid  valid char(1);
alter table taxa change column author_taxon author int(11);
update taxa set unaccept_reason = NULL where name = '';
create table reviews ( id int auto_increment not null, review varchar(40), primary key (id));
insert into reviews (review) select distinct credibility from taxa order by credibility;
create table temp as select taxa.*, reviews.id as review from taxa join reviews on taxa.credibility = reviews.review
alter table temp drop column credibility;
drop table taxa;
alter table temp rename to taxa;
alter table reviews change column id id tinyint;
alter table taxa change column review review tinyint;
create table invalidity_reasons ( id int auto_increment not null, invalidity_reason varchar(50), primary key (id));
insert into invalidity_reasons (invalidity_reason) select distinct unaccept_reason from taxa where unaccept_reason is not null order by unaccept_reason;
create table temp as select taxa.*, invalidity_reasons.id as invalidity_reason from taxa left join invalidity_reasons on taxa.unaccept_reason = invalidity_reasons.invalidity_reason;
alter table temp drop column unaccept_reason;
drop table taxa;
alter table temp rename to taxa;
alter table invalidity_reasons change column id id tinyint;
alter table taxa change column invalidity_reason invalidity_reason tinyint;
alter table taxa change column uncertain_prnt_ind uncertain_print char(1);
alter table kingdoms change column id id tinyint;
alter table taxa change column kingdom kingdom tinyint;
update  taxa set rank_id = rank_id div 5;
alter table taxa change column rank_id rank tinyint;
alter table taxonomic_units rename to ranks;
alter table ranks change column kingdom kingdom tinyint;

